### ISSUE TITLE
Filter logger optimize

### ISSUE THREAD

**Issue by cyrnicolase** [easegress-io/easegress#1169]
I believe the current logging appoach is not particularly user-friendly. Each filter which want to use logger, it needs to modify the `logger package`. 

pkg/logger/export.go
```go
// NewPlainLogger creates a plain logger.
func NewPlainLogger(opt *option.Options, filename string, maxCacheCount uint32) *zap.SugaredLogger {
    return newPlainLogger(opt, filename, maxCacheCount)
}
```

pkg/filters/logger/logger.go
```go
type Logger struct {
    spec *Spec
    l    *zap.SugaredLogger
}

func (f *Logger) Init() {
    opt := f.spec.Super().Options()
    f.l = logger.NewPlainLogger(opt, "my_custom.log", 512)
}

func (f *Logger) Handle() {
    f.l.Info("something need to log")
}

func (f *Logger) Close() {
    y.l.Sync()
}

```

So, I don't need to modify the basic `logger package`.

**Comment by suchen-sci** [comment]
Hi, I am not really understand this... 
Current in easegress, filters can use functions in "github.com/megaease/easegress/v2/pkg/logger" to do the logging. 
For example, `logger.Infof(...)`.

**Comment by cyrnicolase** [comment]
I mean, the filter need to log something into an independent file.

**Comment by suchen-sci** [comment]
So, you want to add an exportable function `NewPlainLogger ` in `pkg/logger/export.go` that can be used in custom filters?
Am i right?

**Comment by cyrnicolase** [comment]
Yes.

**Comment by suchen-sci** [comment]
Sounds good to me. Could you please make a pr for us about it?
