### ISSUE TITLE
[Question]:Is buildOutputResponse missing ?

### ISSUE THREAD

**Issue by cyrnicolase** [easegress-io/easegress#1172]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

https://github.com/megaease/easegress/blob/main/pkg/filters/proxies/httpproxy/wspool.go#L299

![图片](https://github.com/megaease/easegress/assets/2086960/981db207-b0be-4c2d-a91b-5df107178fe7)

When a Websocket connection encounters an error, there will call function `buildFailureResponse` . However, there is not occurence of `ctx.SetOutputResponse(resp)` when the operation is successful. 

Is this intentional in the design?

**Comment by suchen-sci** [comment]
i think when it is successful, the conn may used to write data for websocket directly and easegress not need to handle it. the websocket packet will handle this for us. 

please check the code following
https://github.com/megaease/easegress/blob/main/pkg/filters/proxies/httpproxy/wspool.go#L206

**Comment by cyrnicolase** [comment]
However, I think this approach is incomplete in a request lifetime . I can't obtain the `OutputResponse` from the `ctx` after a `WebsocketProxy`.

**Comment by suchen-sci** [comment]
Hi, this new pr may solve this problem, please check.

**Comment by cyrnicolase** [comment]
That's great！
