### ISSUE TITLE
Filter will be created even it is not referenced in flow

### ISSUE THREAD

**Issue by xxx7xxxx** [easegress-io/easegress#1173]
See this loop:

https://github.com/megaease/easegress/blob/2dc8e9815e62b4e26c2d6b88acf5ac994c6574e7/pkg/object/pipeline/pipeline.go#L263-L296

In my opinion, there is no need and waste of resources to do that, should we only iterate flow to create filters as required.

**Comment by xxx7xxxx** [comment]
@localvar Is this intentional if you remember.

**Comment by localvar** [comment]
yes, that's intentional, the pipeline spec may not define a flow this loop covers the case. And this also follows the behavior of the first version of easegress.

Btw, from v2.0, a filter instance is allowed to appear more than once in the flow.

> @localvar Is this intentional if you remember.

**Comment by xxx7xxxx** [comment]
Fair enough
