### ISSUE TITLE
[Question]: When using Easegress images version V2.6.1 and above, the IngressController does not function properly.

### ISSUE THREAD

**Issue by tjqc0512** [easegress-io/easegress#1235]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

I installed the ingress-controller using helm-charts and followed the Ingress resource example provided in the tutorial. I encountered a problem:

When using version V2.6.1 and below, the requests are responded to normally.
![003](https://github.com/easegress-io/easegress/assets/26787137/f9e2ec0a-f4c4-4c67-a11f-bf3a96d49c00)
However, when the image version is above V2.6.1, although the Easegress ingress-controller appears to be running normally in Kubernetes, it returns a 404 error when a request is sent, and the logs indicate that the corresponding backend service cannot be found.

When using version V2.6.1 and below, entering the Easegress pod and using the egctl get all command shows the following resources:

![001](https://github.com/easegress-io/easegress/assets/26787137/36dc62db-3e2e-4ae1-b0d9-c4e87666ce7c)

However, when the image version is above V2.6.1, entering the Easegress pod and using the egctl get all command shows the following resources:

![002](https://github.com/easegress-io/easegress/assets/26787137/00fe1010-c43d-452e-a245-74d27593855b)
I noticed that with versions above V2.6.1, many more resources appear. Could this be the cause of the issue? Additionally, this problem also occurs when I develop custom filters and package the Easegress image as an IngressController.

**Comment by suchen-sci** [comment]
Hi, resources you have seen is our new feature, it may not cause the problem. I check the release note. During 2.6.1 to 2.6.2, only this pr releated to ingress controller https://github.com/easegress-io/easegress/pull/1089. 
@xxx7xxxx could you please recheck this pr to see if there are some potential problems?

By the way, in easegress 2.7.1, we support check resources created by ingress-controller. Please check this part of doc https://github.com/easegress-io/easegress/blob/main/docs/02.Tutorials/2.1.egctl-Usage.md#viewing-and-finding-resources 
By using the new command, we may find and fix the problem more quickly.

**Comment by xxx7xxxx** [comment]
@tjqc0512  Please post the log of the easegress-ingress-controller. We might get the evidence that causes the error.

**Comment by xxx7xxxx** [comment]
@tjqc0512 Hi, we've released v2.7.2 to address a bug in Ingress Controller, please upgrade Easegress and check it out.

**Comment by tjqc0512** [comment]
@xxx7xxxx 
Thank you very much. After using version 2.7.2, it has returned to normal. Adding easegress.ingress.kubernetes.io/proxy-timeout: "20" to the header of the ingress resource configuration file can also solve the problem.
