### ISSUE TITLE
Easegress Gateway API: Inquiry on Rate Limiter, Circuit Breaker, and HTTP/3 Support

### ISSUE THREAD

**Issue by tjqc0512** [easegress-io/easegress#1362]
Through reading the documentation, I learned that Easegress supports RateLimiter and CircuitBreaker functionality as a Kubernetes Gateway API. We plan to use the Kubernetes Gateway API to replace Ingress to meet our health monitoring needs. I have two questions that I hope you can answer:
When using Easegress as a Kubernetes Gateway API, is it necessary to install any additional software, such as EaseMesh, to enable the RateLimiter and CircuitBreaker functionalities?
How well does Easegress support HTTP/3 traffic as a Kubernetes Gateway API?

_Originally posted by @tjqc0512 in https://github.com/easegress-io/easegress/issues/1361#issuecomment-2527172674_

**Comment by xxx7xxxx** [comment]
1. No need to install EaseMesh, please check out this doc for details: https://github.com/easegress-io/easegress/blob/main/docs/04.Cloud-Native/4.2.Gateway-API.md
2. Set `http3: true` in httpserver spec which leverages https://github.com/quic-go/quic-go/ to run http3 server.

**Comment by tjqc0512** [comment]
Thank you very much for your patient answers.
