### ISSUE TITLE
[feature] Supporting more strategies for traffic coloring

### ISSUE THREAD

**Issue by haoel** [easegress-io/easegress#151]
As we know, canary deployment is a very useful feature to help customers verify the changes from the customer side.

To support this feature well, we need more strategies to do traffic coloring work.  

The following configuration is proposed.

 - **HTTP Request Header  Coloring**
    - **User-Agent**: matching the keyword matching in User-Agent. [high]
    - **Cookie**: Matching the key value in cookies. [high]
    - **Query String**:  the HTTP query string. [high]
    - **IP Address**: matching the IP address support CIDR. [low]   (Notes: IP address might not be a practical solution, because it's very hard to know which IP belongs to who)
   
- **Access Token - JWT or HMAC**
   - Extracting some special string from the service-side token(such, user tags) [high]

**Notes: all of the traffic coloring strategies must be based on the user-side instead of the server-side.**

Meanwhile, we also need a couple of statistics for specific coloring rules.
- The overall percentage traffic coloring.
- The latest 1 hr and 1d percentage traffic coloring.

**Comment by xxx7xxxx** [comment]
We have supported percentage traffic coloring and access token by specifying the header.
