### ISSUE TITLE
extract sending trace function from httpServer and Proxy to a dedicated TraceController 

### ISSUE THREAD

**Issue by qdongxu** [easegress-io/easegress#235]
# Background
Easegress supports opentracing/zipkin. current reporter  should be configured in each httpServer and only supports http reporter for the moment. There're some limitation and drawbacks: 

1. It couples logging issues with the main traffic.  
2. It's hard to extend the target server type, e.g. sending to a Kafka broker. It needs to update the code of httpSever. 
3. Marshaling spans to bytes happens on the main path which handles requests and responses. 

# Proposal
Add a TracingController. Reports spans in the main path to the TracingConroller, the controller should support different reporters. 

# Limitation

A typical way in Easegress is to extend functions by Controller/Pipeline/Filter.  But trace cannot be handled in this way. 

The filter way only works for the httpServer level's tracing. the upstream requests/response was handled inside the `Proxy` filter completely, which could not be detected by other `Filter`.

**Comment by xxx7xxxx** [comment]
Dated proposal
