### ISSUE TITLE
Support variables in configurations

### ISSUE THREAD

**Issue by zhao-kun** [easegress-io/easegress#26]
Like Nginx,  embed variables[1] will make users easy to configure, furthermore, it will bring greater flexibility for configurations. 
For example:
When we want to set an HTTP header in a `requestAdaptor` filter, it better to write 

```yaml
set:
   Host: $host
``` 
then

```yaml
set:
  Host: "xxxx.com"
```

I strongly recommend we introduce the variable mechanism.

[1] https://nginx.org/en/docs/http/ngx_http_core_module.html#variables

**Comment by localvar** [comment]
I think we already have things like this, but in different grammar:

```yaml
    set:
      Host: "[[filter.api-aggregator-example.req.host]]"
```

**Comment by benja-wu** [comment]
## Backgound 
Currently, Easegress has a template mechanism to extract HTTP-related elements from already execution filters, which mean the filter can get some HTTP elements such as `Header`, `Method`, `URL`, `BODY`(only JSON format supported, but we can extract some wanted field in JSON by GJSON syntax), by using a simple template syntax. 
But there are restrictions, in an HTTP pipeline, let's say it has an execution sequence as `A->B->C->D`. 
1.  filter A can't get any elements by using a template.
2. filter D can get `A`, `B`, `C`'s HTTP elements except itself. 
3. filter B can get A's, and filter C can get A, B's HTTP elements.

* We can understand this restriction with this [example](https://github.com/megaease/easegress/blob/main/example/config/http-pipeline-orchestration.yaml)  more clearly. 

## Ideas 
1. Add a `beforeMe` mechanism, which means Easegress HTTP template engine can store a filter's original HTTP req/rsp and the modified HTTP req/rsp to its store for template syntax.
2. Considering supporting extracting the filter itself's HTTP elements in this filter's configuration. 
3. Expand the template syntax extracting target, not only HTTP-related elements but also some system-related elements such as NGINX's. 

 (more detailed discussion and design should be involved. )

**Comment by xxx7xxxx** [comment]
We have supported in filters that use template[1] .

[1] https://github.com/easegress-io/easegress/blob/main/docs/07.Reference/7.02.Filters.md#template-of-builder-filters
