### ISSUE TITLE
Metrics are not following a same principle

### ISSUE THREAD

**Issue by localvar** [easegress-io/easegress#284]
In the calculation of metrics like `request count`, `status code count`, `min duration`, `max duration`, all data are weighted equally.
In the calculation of metrics like `m1`, `m5`, the moving average algorithm is used, which gives more weight to recent data.
Metrics like `duration percentiles` are actually only using the recent data for calculation.

These metrics should follow the same principle to weight data by default, exceptional cases should be handled carefully.

**Comment by xxx7xxxx** [comment]
This difference was explained and not wrong.
