### ISSUE TITLE
How do I persist logs from secondary nodes？

### ISSUE THREAD

**Issue by bobwanglong** [easegress-io/easegress#440]
We need to persist the logs from the secondary nodes on disk，then do aggregate analysis on the logs.However, the current deployment mode does not support this

Can support more persistentVolume methods，eg：nfs,ceph?

**Comment by zhao-kun** [comment]
I have a solution to help you solve your X problem.

Leverage logger collector. Logs can be collected via a dedicated log collector eg: `flunted`, `filebeat`, etc., you could deploy the collector as a DaemonSet resource in K8s. There are many dedicated images that let you collect logs to Kafka or Elasticsearch [1]
- fluent/fluentd-kubernetes-daemonset:v1.14.3-debian-elasticsearch7-1.0 
- fluent/fluentd-kubernetes-daemonset:v1.14.3-debian-kafka-1.0 

I wonder what makes you draw the conclusion that the current deployment mode does not support collecting log? Could you tell me what's your real concern? 

> The Easegress support to deploy in K8s cluster, it obviously should support PersistentVolume, but you need to provision volume yourself and change the corresponding configuration of the Easegress and deployment spec.

- [1] - https://github.com/fluent/fluentd-kubernetes-daemonset

**Comment by zhao-kun** [comment]
Furthermore, the K8s has an offical article [1] to describe how to collect application logs [1], I think it is the best practice for log collecting. I strongly didn't recommend leveraging the PersistentVolume collecting logs. Only if the K8s users want to preserve the status of services, should use persistent volume. So in most cases, PersistenVolume will be used along with the Statefulste application.


[1] https://kubernetes.io/docs/concepts/cluster-administration/logging/
