### ISSUE TITLE
Does `httpfilter.Spec` take into account that if headers are not configured but URL are configured, the URLs are still checked

### ISSUE THREAD

**Issue by aniaan** [easegress-io/easegress#540]
**Is your feature request related to a problem? Please describe.**

This is the logic currently implemented in the main branch:

> If `headers` criteria are configured, a request is filtered in if it matches both headers and urls. If `headers` criteria are NOT configured, the probability options are used.

**Describe the solution you'd like**

I want to take the URL check when no header is configured but the URL is configured, and the approximate logic is described as follows

> If `headers or URL` criteria are configured, a request is filtered in if it matches both headers and urls. If `headers and URL criteria` are NOT configured, the probability options are used.

**Describe alternatives you've considered**

**Additional context**

---
Thanks for contributing 🎉!

**Comment by samutamm** [comment]
This sounds like it wouldn't conflict with existing applications, as only a new case (URL is configured, header is not) is added.
