### ISSUE TITLE
unified objects hierachy

### ISSUE THREAD

**Issue by localvar** [easegress-io/easegress#709]
Currently, some objects in Easegress belong to a namespace (TrafficGates and Pipelines), and we need to use `/<namespace>/<object>/<id>` to access their information, while other objects do not belong to a namespace, and we use `/<object>/<id>` to access their information.

The idea is to put all objects into a namespace, this is to say, we move objects currently not belonging to a namespace to the `default` namespace.

**Comment by xxx7xxxx** [comment]
We fixed X problem in https://github.com/easegress-io/easegress/pull/1197
