### ISSUE TITLE
Informer send notification after closed 

### ISSUE THREAD

**Issue by localvar** [easegress-io/easegress#88]
As discussed in https://github.com/megaease/easegress/pull/79#discussion_r660204660, it is possible for the current mesh informer implementation to send notifications after it is closed, this is unexpected and may cause bugs.

To fix this, we can add a wait operation in `informer.Close` to ensure all notifications are sent before the function returns, the change itself is simple but we need to check the existing code to ensure the `wait` does not cause a deadlock.

If the above solution is not possible, we can document the behavior and let client code handle the delayed notifications.

**Comment by xxx7xxxx** [comment]
@suchen-sci
